name: Node CI/CD Demo with hostinger

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    -name: deploy to hostinger
      host: ${{ secrets.HOSTINGER_HOST }}
      username: ${{ secrets.HOSTINGER_USERNAME }}
      password: ${{ secrets.HOSTINGER_PASSWORD }}
      port: 22

      script: |
        cd /var/www/Node js/loadblacer/cicd-demo
        git pull origin main
        npm install
        pm2 restart app.js
      
        

   

    

   