name: Node CI/CD Demo with Hostinger

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
      - name: server start
        run: npm start &
      - name: Wait for server
        run: sleep 5
      # ✅ Run Tests (NO server start needed if using supertest)
      - name: Run Tests
        run: npm test

      # ✅ Deploy only if tests pass
      - name: Deploy to Server
        if: success()
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 22
          script: |
            cd "/var/www/Node js/loadblacer/cicd-demo"
            git pull origin main
            npm install
            pm2 restart cicdtest
